### ISSUE TITLE
Run command for only one user

### ISSUE THREAD

**Issue by leegalan** [box-community/update-quota#1]
Hello,

I was wondering if there is a way to run this command on only one or just a few of our enterprise users as a test run. This would help make sure it will be ok when we run it on all of our enterprise users.

Thanks for the help.

**Comment by jhoerr** [comment]
Unfortunately not; this tool was purpose-build to update everybody in the enterprise. I would recommend one of:
1. Create a developer enterprise with a non-edu account. Create an app in the developer enterprise and run the tool with that token.
2. Run this against a test edu enterprise if you have one.

If you're comfortable with C# (or even Java), you could also change the code to [accept a command line argument for a single username](https://github.com/box-community/update-quota/blob/master/src/BoxQuotaUpdate/Program.cs#L48) and [pass that username to the Box user query](https://github.com/box-community/update-quota/blob/master/src/BoxQuotaUpdate/Program.cs#L104) as a `filterTerm` the form "username@".

**Comment by leegalan** [comment]
Thanks, John. I'll give this a try.
